- name: Install mysql client
  apt:
    name: libmysqlclient-dev
    state: latest
- name: Download redmine package
  get_url:
    url: 'https://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz'
    dest: /tmp/redmine.tar.gz
    checksum: 'sha256:{{ redmine_checksum }}'
  register: download_redmine_package
- name: Create directory
  file:
    path: /opt/redmine/
    state: directory
- name: Unarchive redmine package
  unarchive:
    src: /tmp/redmine.tar.gz
    dest: /opt/redmine/
    extra_opts: [--strip-components=1]
    remote_src: yes
  when: download_redmine_package.changed
- name: Setup database configuration
  shell:
    chdir: /opt/redmine
    cmd: |
      cat config/database.yml.example \
        | yq -y ".production.adapter = \"mysql2\"" \
        | yq -y ".production.host = \"127.0.0.1\"" \
        | yq -y ".production.username = \"{{ redmine_database_username }}\"" \
        | yq -y ".production.password = \"{{ redmine_database_password }}\"" > config/database.yml
  when: download_redmine_package.changed
- name: Transfer unicorn configuration
  copy:
    src: unicorn.rb
    dest: /opt/redmine/config/unicorn.rb
- name: Check exists unicorn module of Gemfile
  shell:
    chdir: /opt/redmine
    cmd: grep 'gem "unicorn"' ./Gemfile | wc -l
  register: exists_unicorn_count
  changed_when: no
- name: Add unicorn module to Gemfile
  shell:
    chdir: /opt/redmine
    cmd: echo 'gem "unicorn"' >> ./Gemfile
  when: exists_unicorn_count.stdout == '0'
- name: Check exists concurrent-ruby module of Gemfile
  shell:
    chdir: /opt/redmine
    cmd: grep 'gem "concurrent-ruby", "1.3.4"' ./Gemfile | wc -l
  register: exists_concurrent_ruby_count
  changed_when: no
- name: Add concurrent-ruby module to Gemfile
  shell:
    chdir: /opt/redmine
    cmd: echo 'gem "concurrent-ruby", "1.3.4"' >> ./Gemfile
  when: exists_concurrent_ruby_count.stdout == '0'
- name: Remove exists Gemfile.lock
  file:
    path: /opt/redmine/Gemfile.lock
    state: absent
- name: Install dependencies
  environment:
    BUNDLE_PATH: /opt/redmine/vendor/bundle
    BUNDLE_WITHOUT: development:test:rmagick
  shell:
    chdir: /opt/redmine
    cmd: bundle install
- name: Generate secret token
  shell:
    chdir: /opt/redmine
    cmd: bundle exec rake generate_secret_token
- name: Execute migration
  environment:
    RAILS_ENV: production
  shell:
    chdir: /opt/redmine
    cmd: bundle exec rails db:migrate
- name: Exists theme
  stat:
    path: /opt/redmine/public/themes/bs-redmine-theme-dark
  register: exists_theme
- name: Clone theme
  git:
    repo: https://github.com/Bezvastudio/bs-redmine-theme-dark.git
    dest: /opt/redmine/public/themes/bs-redmine-theme-dark
    version: '{{ redmine_theme_version }}'
  when: exists_theme.stat.exists == false
- name: Start service
  systemd:
    name: redmine
    daemon_reload: yes
    state: restarted
